import { z } from "zod";

import { guidSchema, isValidBusinessDate, isValidSourceDateTime } from "./orders-normalization-helpers.js";

const openEnumSchema = z.string().min(1);
const sourceDateTimeSchema = z.string().min(1).refine(isValidSourceDateTime, { message: "must be a zoned ISO-8601 date-time" });
const businessDateSchema = z.number().int().refine(isValidBusinessDate, { message: "must be a valid yyyyMMdd date" });
const sourceMoneySchema = z.number().finite();
const sourceReferenceSchema = z.object({ guid: z.union([z.string().min(1), z.null()]).optional(), multiLocationId: z.union([z.string().min(1), z.null()]).optional() }).passthrough();
const sourceServerReferenceSchema = z.object({ guid: guidSchema }).strip();
const sourceAppliedTaxRateReferenceSchema = z.object({ guid: z.union([guidSchema, z.null()]).optional(), multiLocationId: z.union([z.string().min(1), z.null()]).optional() }).passthrough().superRefine((value, context) => { if (value.guid == null && value.multiLocationId == null) context.addIssue({ code: "custom", message: "must contain a valid GUID or nonempty multi-location identifier" }); });
const sourceAppliedTaxSchema = z.object({ guid: guidSchema, taxRate: sourceAppliedTaxRateReferenceSchema, rate: z.number().finite().optional().nullable(), taxAmount: z.number().finite(), type: openEnumSchema.optional().nullable(), facilitatorCollectAndRemitTax: z.boolean().optional().nullable() }).passthrough();
const sourceRefundSchema = z.object({ refundAmount: sourceMoneySchema, tipRefundAmount: sourceMoneySchema, refundDate: sourceDateTimeSchema.optional(), refundBusinessDate: businessDateSchema.optional() }).passthrough();
export const sourceRefundDetailsSchema = z.object({ refundAmount: sourceMoneySchema, taxRefundAmount: sourceMoneySchema }).passthrough();
const sourceAppliedDiscountSchema = z.object({ guid: guidSchema, discountAmount: sourceMoneySchema, nonTaxDiscountAmount: sourceMoneySchema, discount: sourceReferenceSchema.optional().nullable(), discountType: openEnumSchema.optional().nullable(), processingState: openEnumSchema.optional().nullable() }).passthrough();
const sourceAppliedServiceChargeSchema = z.object({ guid: guidSchema, chargeAmount: sourceMoneySchema, serviceCharge: sourceReferenceSchema, chargeType: openEnumSchema.optional().nullable(), gratuity: z.boolean(), serviceChargeCategory: openEnumSchema.optional().nullable(), appliedTaxes: z.array(sourceAppliedTaxSchema).default([]), refundDetails: sourceRefundDetailsSchema.optional().nullable() }).passthrough();
const sourcePaymentSchema = z.object({ guid: guidSchema, type: openEnumSchema, amount: sourceMoneySchema, tipAmount: sourceMoneySchema, paidDate: sourceDateTimeSchema.optional(), paidBusinessDate: businessDateSchema.optional(), paymentStatus: openEnumSchema.optional().nullable(), refundStatus: openEnumSchema.optional().nullable(), refund: sourceRefundSchema.optional().nullable(), voidInfo: z.object({ voidDate: sourceDateTimeSchema.optional(), voidBusinessDate: businessDateSchema.optional() }).passthrough().optional().nullable(), otherPayment: sourceReferenceSchema.optional().nullable() }).passthrough();
export const sourceSelectionSchema = z.object({ guid: guidSchema, item: sourceReferenceSchema.optional().nullable(), itemGroup: sourceReferenceSchema.optional().nullable(), optionGroup: sourceReferenceSchema.optional().nullable(), salesCategory: sourceReferenceSchema.optional().nullable(), diningOption: sourceReferenceSchema.optional().nullable(), quantity: z.number().finite(), unitOfMeasure: openEnumSchema.optional().nullable(), selectionType: openEnumSchema.optional().nullable(), price: sourceMoneySchema, preDiscountPrice: sourceMoneySchema, tax: sourceMoneySchema.optional(), deferred: z.boolean(), voided: z.boolean(), voidDate: sourceDateTimeSchema.optional(), voidBusinessDate: businessDateSchema.optional(), appliedDiscounts: z.array(sourceAppliedDiscountSchema).default([]), appliedTaxes: z.array(sourceAppliedTaxSchema).default([]), refundDetails: sourceRefundDetailsSchema.optional().nullable(), modifiers: z.array(z.unknown()).default([]) }).passthrough();
export const sourceCheckSchema = z.object({ guid: guidSchema, amount: sourceMoneySchema, taxAmount: sourceMoneySchema, totalAmount: sourceMoneySchema, taxExempt: z.boolean().default(false), deleted: z.boolean(), voided: z.boolean(), voidDate: sourceDateTimeSchema.optional(), voidBusinessDate: businessDateSchema.optional(), paymentStatus: openEnumSchema, selections: z.array(z.unknown()), payments: z.array(sourcePaymentSchema).default([]), appliedServiceCharges: z.array(sourceAppliedServiceChargeSchema).default([]), appliedDiscounts: z.array(sourceAppliedDiscountSchema).default([]) }).passthrough();
export const sourceOrderSchema = z.object({ guid: guidSchema, businessDate: businessDateSchema.optional().nullable(), openedDate: sourceDateTimeSchema.optional(), modifiedDate: sourceDateTimeSchema.optional(), promisedDate: sourceDateTimeSchema.optional().nullable(), approvalStatus: openEnumSchema.optional().nullable(), source: openEnumSchema.optional().nullable(), server: sourceServerReferenceSchema.optional().nullable(), diningOption: sourceReferenceSchema.optional().nullable(), revenueCenter: sourceReferenceSchema.optional().nullable(), restaurantService: sourceReferenceSchema.optional().nullable(), numberOfGuests: z.number().int().min(0).optional(), excessFood: z.boolean(), deleted: z.boolean(), voided: z.boolean(), voidDate: sourceDateTimeSchema.optional(), voidBusinessDate: businessDateSchema.optional(), checks: z.array(sourceCheckSchema).min(1) }).passthrough();
export type SourceOrder = z.infer<typeof sourceOrderSchema>;
export type SourceCheck = z.infer<typeof sourceCheckSchema>;
export type SourceSelection = z.infer<typeof sourceSelectionSchema>;
export type SourcePayment = z.infer<typeof sourcePaymentSchema>;
export type SourceAppliedTax = z.infer<typeof sourceAppliedTaxSchema>;
export type SourceAppliedServiceCharge = z.infer<typeof sourceAppliedServiceChargeSchema>;
export type SourceAppliedDiscount = z.infer<typeof sourceAppliedDiscountSchema>;
export type SourceReference = z.infer<typeof sourceReferenceSchema>;
